### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by gzebec** [apex-plugins/Address-Picker#1]
Hi,
I just finished installing and setting up your great plugin, but it doesn't seems to be working.
Map is not shown. I have a valid Google Maps Key.

Br,
Goran

**Comment by apex-plugins** [comment]
Hello,
Can you check what item template you are using. Make sure no templated related in item appearance. 
Please check without template and let me know if any issues.
Thanks

**Comment by apex-plugins** [comment]
Hello,
I have resolved template issue. Please download latest release.
Thanks

**Comment by gzebec** [comment]
I tried with every item template and I noticed that if **Dynamic Width** is set, map doesn't show.
I think the problem ih is that parameter. When the actual value is set then the map is visible. 
You have a bug in your code on fetching attributes data.

    -- Component Plugin Attributes
    V_COUNTRY := P_ITEM.ATTRIBUTE_01;
    V_SHOW_GMAP := P_ITEM.ATTRIBUTE_02;
    V_MAP_WIDTH := P_ITEM.ATTRIBUTE_03;
    V_MAP_HEIGHT := P_ITEM.ATTRIBUTE_04;
    V_MAP_ZOOM := NVL(P_ITEM.ATTRIBUTE_05,10);
    V_POSITION := P_ITEM.ATTRIBUTE_06;
    V_C_LATITUDE := NVL(P_ITEM.ATTRIBUTE_07,0);
    V_C_LONGITUDE := NVL(P_ITEM.ATTRIBUTE_08,0);
    **V_DYNAMIC_WIDTH := NVL(P_ITEM.ATTRIBUTE_08,0);** -- this must be attribute 09.

**Comment by apex-plugins** [comment]
Thanks for spotted issue. The code in GitHub release might be old and that causing issue. Please check with latest code which has template issue resolved.

**Comment by gzebec** [comment]
It's ok now. 
Thanks.

**Comment by gzebec** [comment]
Is it possible to get explanation how to retrieve address, latitude and longitude from your plugin as seen in you demo app?

**Comment by apex-plugins** [comment]
Data stored in son formate. 
Following is the sample json:
{"ADDRESS_DATA" : {"LATITUDE" : "20.9366102", "LONGITUDE" : "72.94028660000004", "ADDRESS" : "Central Bazar Mall, Opp Vidya Kunj School, Lunsikui road, Pratiksha Society, Navsari, Gujarat 396445, India"}}

You can use dynamic action to set Latitude, Longitude and Address values to different item.
e.g.
var obj = JSON.parse($v("P1_RAW_DATA")); 
$s(P1_LATITUDE, obj.ADDRESS_DATA.LATITUDE);
$s(P1_LONGITUDE, obj.ADDRESS_DATA.LONGITUDE);
$s(P1_ADDRESS, obj.ADDRESS_DATA.ADDRESS);

**Comment by fecola** [comment]
Where I found tha JSON?

Which type of dynamic action I should creat?

My plugin works very well. I created the items P8_RAW_DATA, P8_LATITUDE, P8_LONGITUDE and P8_ADDRESS.

**Comment by apex-plugins** [comment]
Create dynamic action on Change event of P8_RAW_DATA item and add Execute Javascript Code action with below source.
var obj = JSON.parse($v("P8_RAW_DATA"));
$s(P8_LATITUDE, obj.ADDRESS_DATA.LATITUDE);
$s(P8_LONGITUDE, obj.ADDRESS_DATA.LONGITUDE);
$s(P8_ADDRESS, obj.ADDRESS_DATA.ADDRESS);

**Comment by fecola** [comment]
Just it?
My item P8_RAW_DATA, don't get any value, after select the address. There are any configuration that I do before use?

**Comment by apex-plugins** [comment]
No it will not require any additional configuration. Check if $v("P8_RAW_DATA") getting value after selection address in console.

**Comment by fecola** [comment]
Sorry for late, my APEX cloud was out of service.
I tried rigth now, and my P8_RAW_DATA, not are getting any value from address

**Comment by apex-plugins** [comment]
Could you send me screenshot of your configuration and runtime display of plugin.

**Comment by fecola** [comment]
Do you have a email? I make a little video and sent to you

**Comment by apex-plugins** [comment]
sent it to kp9985@gmail.com

**Comment by fecola** [comment]
ok, sent thanks

**Comment by apex-plugins** [comment]
You have to use P8_PLUGIN item to get the data. So data stored in item P8_PLUGIN and you have to get from that. Instead of using plugin in P8_PLUGIN use in P8_RAW_DATA item.

**Comment by fecola** [comment]
Woooow, nice man...perfect.
But, we only can it works, put dynamic action to change value item plugin, at P8_RAW_WORK.
When change plugin, it works perefectly
