### ISSUE TITLE
What parameters do I need to redirect and edit the map?

### ISSUE THREAD

**Issue by jcarlos314** [apex-plugins/Address-Picker#2]
Hello, first of all thank you for making this amazing pluggin. I have a question, What values does the pluggin need to edit the information of the map?

![image](https://user-images.githubusercontent.com/57166132/108112871-93d4ff80-704b-11eb-92ff-4cf7a3df692d.png)

![image](https://user-images.githubusercontent.com/57166132/108112897-9c2d3a80-704b-11eb-9f0e-d58f606cbf6e.png)

 In your demo it redirects to the page of the map and it shows the information and position that I had. What parameters do I need to have it like in your demo?

Thanks again.

**Comment by apex-plugins** [comment]
You need to add values in JSON. See Raw Data column that exact values you need to add to view the information.
